### ISSUE TITLE
Doorbell event

### ISSUE THREAD

**Issue by schwickster** [NRCHKB/node-red-contrib-unifi-os#12]
Hey,

I would love to create a nodered event when the G4 doorbell is pressed, I get a websocket trigger. I tried using your plugin but the websocket doesn't work.

To help you on your way, I figured the following out:
There's a websocket for which shows the doorbell popup when opening a protect page. The url is wss://192.168.1.1/proxy/protect/ws/updates?lastUpdateId=2cdea4f6-cb22-4dfe-8bc1-2c866f3516bf. It sends binairy files which are described here: https://github.com/hjdhjd/homebridge-unifi-protect and here https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/src/protect-api-updates.ts

The lastUpdateId you can get using https://192.168.1.1/proxy/protect/api/bootstrap (in JSON lastUpdateId field).

Would love to get that websocket working!

Thanks

**Comment by Shaquu** [comment]
@crxporter Something new :)
I am going to look at it soon.

**Comment by crxporter** [comment]
This is actually the main goal why I wanted to make this plugin. It's essentially what started the project.

All other information can be gathered by HTTP requests. 

This request is essentially to monitor the live updates from UniFi Protect including but not limited to:
- motion alerts
- doorbell alerts
- smart detections from G4 cams
- night IR light on/off statu
-  likely the new sensor data...

So - yes. This is a huge very important goal of the project.


Shaquu - the incoming data is going to be in binary form. There are some bits which will tell where the JSON starts and ends, it will need to be loaded as a buffer then parsed.

[This](https://github.com/khrrsn/homebridge-unifi-protect-platform/blob/master/dev/stream.ts) is a dev test of what we are looking for. I haven't actually tried it but potentially the output on this script will be the exact JSON payloads we want to pump into nodered.

**Comment by schwickster** [comment]
Good to here. I did read the readme, but thought maybe the info I provided wasn´t something you were aware off.

**Comment by Shaquu** [comment]
@schwickster if it is related to UniFi Protect API then you should try 0.3.0 #23

**Comment by crxporter** [comment]
I've got a bell. Confirmed this works - readme has been updated with some instructions as well.

Please provide any feedback or comments you have! Thanks!

**Comment by schwickster** [comment]
Yup I finally tested it for a few days. Getting a lot of error 1002 and 4000 though
