### ISSUE TITLE
WebSocket Error 1002

### ISSUE THREAD

**Issue by TestUser0000000001** [NRCHKB/node-red-contrib-unifi-os#22]
NodeRed running on node v12

NodeRed Module locks up and needs "Flow Re-Deploy" to work again.
Stops at (WebSocket.js [Here](https://github.com/NRCHKB/node-red-contrib-unifi-os/blob/8793d3eab6eccf442566de170494f1a460f7c820/src/nodes/WebSocket.ts#L108))
Im not sure what the real issue is as the logging only states WS 1002.
This happens after the system has been running for a while OR sometimes on UDMP reboot while NodeRed WS is connected.
If I get more info ill update here, or if I find fix.

**Comment by Shaquu** [comment]
@TestUser0000000001 can you try again?
This time run node-red with `DEBUG=UniFi*` env variable
Also try our latest version 0.3.0

**Comment by crxporter** [comment]
How often are you seeing these? And which endpoint are you using?

When you set debug, note it is case sensitive `UniFi*` 

To figure out where to set it, we need to know how you run nodered...
-if docker, you set debug somewhere in the docker config
-if running manually, you add it to your `node-red start` command
-if running using systemd script, you add the debug to part of the systemd script

**Comment by Shaquu** [comment]
@TestUser0000000001 @schwickster 

1. Please try the latest dev version https://www.npmjs.com/package/node-red-contrib-unifi-os/v/0.7.0-dev.4
2. For debug run node-red with `DEBUG=UniFi*` environment variable. Example `DEBUG=UniFi* node-red`
