### ISSUE TITLE
Crashes node red 2.0.5 after a "full restart flows"

### ISSUE THREAD

**Issue by 0rsa** [NRCHKB/node-red-contrib-unifi-os#27]
node-red @ 2.0.5
node-red-contrib-unifi-os @ 0.5.0

When I restart all my flows in node-red, my server crashes.

Log debug:

`15 Aug 06:01:56 UniFi-Error Bad response from: https://192.168.100.60/api/logout +0ms
15 Aug 06:01:56 UniFi-Error Endpoint not found: Error: Request failed with status code 404 +8ms
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Endpoint not found
    at /nodered/node_modules/node-red-contrib-unifi-os/build/nodes/unifi.js:95:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)`

**Comment by 0rsa** [comment]
Correct logout URL seems to be: /api/auth/logout

**Comment by crxporter** [comment]
@Shaquu

**Comment by 0rsa** [comment]
Cloud Key Gen2 Plus

**Comment by Shaquu** [comment]
I guess endpoint can differ between hardware? I will look at it.

**Comment by Shaquu** [comment]
@0rsa please test on latest dev version

**Comment by Shaquu** [comment]
Please open new issue if the problem persist.
