### ISSUE TITLE
Controller TCP Port can not be defined

### ISSUE THREAD

**Issue by peysche** [NRCHKB/node-red-contrib-unifi-os#36]
Hi,

My Controller is running under a different TCP Port as the default Port.
There is no way to set the endpoint to a different port as 8443.

Regards&Thx

**Comment by Shaquu** [comment]
@peysche please test on latest dev version
For now, you should be able to use custom port for http requests.

If you also need it for websocket then let me know.

**Comment by marcus-j-davies** [comment]
This should be closed.
