### ISSUE TITLE
"failed to log out" Error from Configuration Node

### ISSUE THREAD

**Issue by mwolter805** [NRCHKB/node-red-contrib-unifi-os#44]
Hello,
Thank you for creating this node. Everything appears to work well (I am only using a single unifi-request node) except for this error appearing in the debug window when doing a deploy.
![Screen Shot 2022-06-18 at 6 10 17 PM](https://user-images.githubusercontent.com/24851651/174461784-c21191e9-31ef-4b80-a918-ecae0702f9f8.jpg)

There are only a few things different than most setups. Instead of using an IP, I'm using an internally resolvable URL, port used is 443 and there is a valid public SSL certificate on the controller. 

Please let me know if any additional info is needed.

**Comment by marcus-j-davies** [comment]
This is now fixed in our latest BETA
