### ISSUE TITLE
Protect node - duplicated cameras in list

### ISSUE THREAD

**Issue by crxporter** [NRCHKB/node-red-contrib-unifi-os#52]
@marcus-j-davies - I'm leaving this here as a reminder whenever you're on this project again. 

There is some erratic behavior with the drop-down camera selection on the new Protect node. I'm getting 2 and sometimes 3 copies of my cameras list in the protect node setup:
![Screenshot 2023-01-04 at 7 14 13 AM](https://user-images.githubusercontent.com/38265886/210563168-f901e313-1570-4286-bd09-6827b6597e9b.png)

How is this list being populated? Using bootstrap? The duplicates are appearing when I close and re-open the config of the protect node(s).

**Comment by marcus-j-davies** [comment]
Noted!

I thought I'd fixed that.
I'll use ChatGPT to correct it 😉

**Comment by crxporter** [comment]
Hmm. Palette Manager shows I'm running 0.8.0 ? I don't remember which exact version.

**Comment by marcus-j-davies** [comment]
@crxporter 
This is now fixed in the BETA-2 PR (and I didn't use ChatGPT 😉 )

https://github.com/NRCHKB/node-red-contrib-unifi-os/pull/53
