### ISSUE TITLE
[Enhancement] : Allow custom WS port

### ISSUE THREAD

**Issue by ys333193** [NRCHKB/node-red-contrib-unifi-os#54]
It appears WebSocket interface only uses port 443, and doesn't use port configured in the configuration node.
My Unifi controller runs on port 8443, and WebSocket interface bound to the same port (tested with Python script).

Please expose WebSocket port through config node.

**Comment by Shaquu** [comment]
Hey, so to clarify.
The WebSocket port is configurable from the unifi side.
But on the node side, there is no way at the moment to use a custom port.

**Comment by SgtErnestBilko** [comment]
I can find no setting to change the websocket port in the legacy or new interfaces of UniFi Network Application. 

I can connect using the request node (e.g. endpoint /api/self) on port 8443.

If I try a websocket request using  8443 in NodeRed controller, I get.  

```
28 Jan 07:04:17 UniFi-Error:WebSocket:466be400826b54fa53338f2385f4a769 [UniFi:b24398dbbc492294:b24398dbbc492294] Is UniFi server down? +1ms
28 Jan 07:04:17 - [error] [unifi-web-socket:UniFi:b24398dbbc492294] Error: connect ECONNREFUSED ::1:443
28 Jan 07:04:17 UniFi-Error:WebSocket:5a1259bfaddf9e7669c5bee34f498ffb [UniFi:b24398dbbc492294:b24398dbbc492294] Error: connect ECONNREFUSED ::1:443 +0ms
```

if I use 443 in NodeRed controller I get

`28 Jan 07:15:11 UniFi-Error Bad response from: https:/mymac.local:443/api/login +5s`

Hope that helps.  Let me know if there is anything else you would like me to test.

**Comment by ys333193** [comment]
Thanks for checking!
I was able to call API, but was getting Connection Reset (1006) error using WebSockets.  I have a firewall between Unifi controller and NodeRed server, and both 443 and 8443 ports were opened.  I didn't capture any firewall violations either.
I switched to a different node red contrib node (node-red-contrib-unifi-events) and its WebSocket implementation is working without any errors.

**Comment by crxporter** [comment]
> I switched to a different node red contrib node (node-red-contrib-unifi-events)

While I certainly wouldn't recommend sticking with a 3 years old abandoned project based on a 5 years old project...

I dug a little there and it looks like yes - the websockets there are using port 8443 @Shaquu or @marcus-j-davies see [here](https://github.com/hobbyquaker/ubnt-unifi/blob/68a81666ea39c839a3881b7ea23f8da8898e65f3/index.js#L68)

Perhaps we need to add a field for port in the websocket node. UniFi OS is happy using port 443 but the standalone controllers appear to keep that on 8443. 

Maybe we also add a "default ws port" setting to our `Endpoints.ts` file?

**Comment by crxporter** [comment]
@SgtErnestBilko or @ys333193 

Can one of you try the current websocket node pointed to this endpoint- `:8443/wss/s/default/events`
![image](https://user-images.githubusercontent.com/38265886/215295126-c6274be3-3f99-4482-b7df-87fb622f3ddc.png)

I'm looking at how the connection is made... that might work.

**Comment by SgtErnestBilko** [comment]
That does work :-)

**Comment by ys333193** [comment]
> @SgtErnestBilko or @ys333193
> 
> Can one of you try the current websocket node pointed to this endpoint- `:8443/wss/s/default/events` 

Works for me too!

**Comment by crxporter** [comment]
Awesome!

I'm glad we have found the problem and have a temporary fix. We should leave this issue open until a more permanent solution is added to the node as discussed above.

**Comment by marcus-j-davies** [comment]
@crxporter, @SgtErnestBilko, @ys333193 

The below commit now adds the ability to specify a custom WS port. The defaults are applied according to your selected appliance 

https://github.com/NRCHKB/node-red-contrib-unifi-os/commit/58ad3bf7a8e2d12d06803be6608ab877c1b63598

![Screenshot 2023-02-16 at 16 51 28](https://user-images.githubusercontent.com/55892693/219433141-6a2e3928-5a72-4db6-b793-3ad1b82c4172.png)

**Comment by crxporter** [comment]
Quick note for those who have used my work-around...

This will break your setup unless you now remove the port number from the websocket endpoints. This is the better solution and should be ready in the next beta version.
