### ISSUE TITLE
Bad response from protect when not installed

### ISSUE THREAD

**Issue by tethlah** [NRCHKB/node-red-contrib-unifi-os#66]
I have a UDM Pro and a UNVR.  I have two separate configurations for each appliance,  Those configurations are pointed at the appropriate IP for that appliance. The config for the UNVR is going to "/proxy/protect/api/bootstrap" which is working fine.  I have 3 nodes using my config node for the UDM Pro that pointed to "/proxy/network/api/s/default/stat/alluser", "/api/ws/system", and "/proxy/network/wss/s/default/events".  For some reason the config node for my UDM Pro is throwing the following two errors: 
"Bad response from: https://UDMPRO_IP/proxy/protect/api/bootstrap"  followed by "Endpoint not found: AxiosError: Request failed with status code 404"

The weird thing is that the protect endpoint is in use on my config node with the UNVR IP address on it, but it's the network config node that's pointed at the UDM Pro IP that's throwing the error from the other configuration's endpoint.  This just started about a week ago, and the UDM Pro doesn't even have protect installed.  Makes no sense as to why that config node is throwing an error for an endpoint used on a different config node, especially when the other config node is working fine.

**Comment by crxporter** [comment]
I have the same setup - this error started when the new protect node was added because we started to grab the bootstrap in order to populate the cameras list. That list is populated at each "login" but there is no way (yet) to disable it for the UniFi OS instance *without* protect.

@marcus-j-davies I believe you should be seeing this as well now that you've put your Protect over to a cloud key gen 2 plus. If you've disabled Protect on your Dream Router... 

The easiest fix might be to add a check box in the controller config to say whether this controller has Protect? 

Maybe we change to show 2 options - "console with protect" and "console without protect" in this menu:
![image](https://github.com/NRCHKB/node-red-contrib-unifi-os/assets/38265886/02aec5c9-b702-44ec-b80f-2002362eef42)

Just need some way to say "there's no Protect" so we don't keep trying to grab that bootstrap forever...

**Comment by marcus-j-davies** [comment]
Yeah - we need a way to detect that there is no bootstrap to grab, ill play with it this weekend

**Comment by crxporter** [comment]
Looking over things very quickly...

The websocket `/api/ws/system` should exist for any controller.

Updates come in very often of type `DEVICE_STATE_CHANGED` which have the following JSON key `payload.apps.controllers[1].isRunning`

![image](https://github.com/NRCHKB/node-red-contrib-unifi-os/assets/38265886/192f76bb-de7b-4379-b0ef-29d288326dde)

I would think that we need the protect instance to exist there - and to be running - if we expect a cams bootstrap will exist.

Watching that  will even show whether the protect instance is actually running (not restarting or stopped) when you try to pull the bootstrap? There could be something there?

**Comment by tethlah** [comment]
Well what doesn't make sense is that the error is for "/proxy/protect/api/bootstrap" even though I'm not calling it.  Even if I disable the one calling "/api/ws/system" it still happens.  This just started a couple weeks ago, I've been using this exact flow for months with no changes and it never happened until a couple weeks ago.

**Comment by marcus-j-davies** [comment]
As already mentioned by @crxporter 

"we started to grab the bootstrap in order to populate the cameras list" - therefore it's us, not you.

It will be fixed this weekend if i get time.

**Comment by crxporter** [comment]
> This just started a couple weeks ago

It would have started when you updated the plugin to version 0.9.0 - the endpoint is being called in the background by the `unifi-access-controller-node` node and is be used to populate the cameras list on controllers that have Protect running. We didn't (yet) consider the case of controllers that don't have protect running...

I noticed this error a while ago and mentioned it to Marcus, but we didn't deal with it yet. 

A quick fix if you don't want to see the errors while it's being fixed - just install and start the Protect app on your UDM. No need to add any cameras, just having the app running will make the error go away.

**Comment by tethlah** [comment]
Will that not mess with protect on the other system?  I migrated protect from my UDM Pro to UNVR so I had it installed previously...

**Comment by crxporter** [comment]
They act fully independent of each other. Having a protect instance on the udm won't do anything to the running system on the unvr. 

The udm protect won't even see the cameras since they're already adopted. If you click into it you'll just the splash screen of how to get started or something

**Comment by marcus-j-davies** [comment]
This should be fixed in V1.0.0
