### ISSUE TITLE
Animal detection support

### ISSUE THREAD

**Issue by Supergiovane** [NRCHKB/node-red-contrib-unifi-os#70]
Hi,
is it possible to add the animal detection? Thank you.

**Comment by Shaquu** [comment]
Yes but using another nodes :) @crxporter did it!

**Comment by crxporter** [comment]
Hehe - I did it with tensorflow!

It should be possible with some careful searching of the camera websocket messages. I'll try digging around next time I'm working on my automation! Might be a week or so, ping me if I don't respond again soon

**Comment by marcus-j-davies** [comment]
This is now available with v1.0.0 Dev 2

available by running, and using the Protect Node
```
npm install node-red-contrib-unifi-os@dev
```

**Comment by Supergiovane** [comment]
Thank you!

**Comment by marcus-j-davies** [comment]
![Screenshot 2024-04-28 at 16 55 14](https://github.com/NRCHKB/node-red-contrib-unifi-os/assets/55892693/5f02290d-f2a0-4afa-a746-27c8c075a888)
