### ISSUE TITLE
missing line crossing motion events 

### ISSUE THREAD

**Issue by jurajs5** [NRCHKB/node-red-contrib-unifi-os#73]
Hi,  in new version I am missing line crossing notification. 

Are you able to identity name of event in notification as additional information? I have multiple line crossing and need to know which is was activated.

thank you
Juraj

**Comment by marcus-j-davies** [comment]
Hi @jurajs5 

providing the event has a unique fingerprint.
We will review the event soon.

Regards

**Comment by marcus-j-davies** [comment]
@jurajs5 

Line Crossing Now Supported.
I'll try and get it out in a few days


![image](https://github.com/NRCHKB/node-red-contrib-unifi-os/assets/55892693/2d4f2946-d207-4e43-a8f2-9102b37ae15c)

**Comment by jurajs5** [comment]
would love to test, pls public new version

**Comment by marcus-j-davies** [comment]
Closing as this  has been aded in Beta 3
