### ISSUE TITLE
Licence plate not working + Initalized stuck

### ISSUE THREAD

**Issue by itashi37** [NRCHKB/node-red-contrib-unifi-os#80]
Hello sorry to bother , I'm in love with your plugin , and first of all I wanted to thank you for all the work done .

since the update , It is possible to get notifications like license plate and vehicule detection , the vehicle detection work like a charm but not the license plate , I use AI camera , I can see it in unifi protect but nothing in node red ? did I make something wrong ? and , I don't know what is happening but sometimes every camera are stuck in initialized , and not connected , I made a local account and all , what's going on there ? , I have to modify user and after that it's working again do you have any idea how to fix it ?
thank you

**Comment by Shaquu** [comment]
@crxporter ? :)

**Comment by crxporter** [comment]
I don't have anything with license plate recognition... the plugin definitely could handle this but I don't know that we have added it yet. 

Have you seen the newest Unifi protect plugin though? You can send webhook notifications from Unifi to any endpoint (nodered http node)

take a look:
https://community.ui.com/releases/UniFi-Protect-Application-4-1-50/7ce33b96-8ba1-4788-9569-038f46c2e34b

**Comment by crxporter** [comment]
![image](https://github.com/user-attachments/assets/e03c320c-91a9-4d09-ac42-c0bb72e7eaaa)
There's an example of what the http post looks like

**Comment by crxporter** [comment]
...and I'm an idiot...

I just read better and realized you do have notifications but are being logged out. 

I have noticed this a few times - usually when Unifi restarts while nodered stays online. I have brought it up with @marcus-j-davies but he's quite busy lately

**Comment by marcus-j-davies** [comment]
This will get looked at when time allows.
presently, this is not supported.

Closing in the mean time
